### ISSUE TITLE
Brief Question About Internal Interface

### ISSUE THREAD

**Issue by alinebrito** [nosslin579/smigo#1]
Dear developer,

I am a master student at UFMG, Brazil. Currently, I am researching the use of internal interfaces by client projects. I mean, public interfaces for use only by internal modules (e.g., com.google.inject.internal.Maps). Your feedback will help to guide our research.
1. You used an internal interface in `LogHandler` class of your project. Did you know that it is an internal interface of the Google Inject library?
2. Are you aware that internal interfaces are unstable and may change without backward-compatibility?

Interface:  `com.google.inject.internal.Lists`
File: [LogHandler.java](https://github.com/nosslin579/smigo/blob/e8e9c69060a18f1b115a5e96c6c62a9fd55a8cd4/src/main/java/org/smigo/log/LogHandler.java)
Line: 25

**Comment by nosslin579** [comment]
Hi,
1, I had not noticed it is an internal.
2, Yes.

Now that you have pointed it out, I will probably change it.

**Comment by alinebrito** [comment]
Hi,
Thank you for your feedback!
