### ISSUE TITLE
Could not find artifact kga:kga:jar:1.8.1 in central

### ISSUE THREAD

**Issue by oscr** [nosslin579/smigo#2]
The build seems to be broken. When running mvn test I get the following error:

[ERROR] Failed to execute goal on project smigo: Could not resolve dependencies for project org.smigo:smigo:war:1.0-SNAPSHOT: Could not find artifact kga:kga:jar:1.8.1 in central (http://repo.maven.apache.org/maven2) -> [Help 1]

**Comment by nosslin579** [comment]
This dependency must be downloaded from [SourceForge](https://sourceforge.net/projects/kitchengarden/) and added to local repo with 

`mvn install:install-file -Dfile=KitchenGardenAid.1.8.1.jar -DgroupId=kga -DartifactId=kga -Dversion=1.8.1 -Dpackaging=jar`

 or you can comment out dependency and KitchenGardenAidDataTest.

**Comment by oscr** [comment]
Would it be possible to provide a "get up and running" section for the readme/other document? For example what is in your "local.properties" that's needed to run mvn test, what db + version are you running and so on. To ensure that we're starting on the same page :)

**Comment by nosslin579** [comment]
I have added an Up-and-running section to readme.md. Take a look and tell me if anything is missing.
